apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: mysql-config
        # env:
        #   - name: MYSQL_ROOT_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: mysql-secret 
        #         key: MYSQL_ROOT_PASSWORD
        #   - name: MYSQL_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: mysql-secret
        #         key: MYSQL_PASSWORD
        #   - name: MYSQL_DATABASE
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mysql-config
        #         key: MYSQL_DATABASE
        #   - name: MYSQL_USER
        #     valueFrom:
        #       configMapKeyRef:
        #         name: mysql-config
        #         key: MYSQL_USER                  

        # env:
        #   - name: MYSQL_ROOT_PASSWORD
        #     value: R12345r
        #   - name: MYSQL_PASSWORD
        #     value: Clarusway_1
        #   - name: MYSQL_DATABASE
        #     value: phonebook
        #   - name: MYSQL_USER
        #     value: clarus 
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-volume
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim